version: 0.2
 
phases:

  pre_build:
    commands:
      - echo pre_build 1
  build:
    commands:
      - mvn clean install
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - target/tmbv-travel-admin-0.0.2.jar